version: '3.8'
 
services:
  # Banco de dados MySQL
  db:
    image: mysql:8.0
    container_name: wp_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: senha_root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: senha_wordpress
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wp_network
 
  # WordPress
  wordpress:
    image: wordpress:latest
    container_name: wp_app
    restart: always
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: senha_wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wp_data:/var/www/html
    ports:
      - "8080:80"
    networks:
      - wp_network
 
# Definições de volumes e rede
volumes:
  db_data:
  wp_data:
 
networks:
  wp_network:
    driver: bridge